### ISSUE TITLE
Cannot use priority multiple times

### ISSUE THREAD

**Issue by mbuettner** [hartez/todo.txt-PowerShell#10]
I noticed that the script prevents using one priority multiple times and gives an error

    There is already an item with this priority

I haven't used todo.txt CLI but looking at the code it doesn't seem to have such a restriction, and looking [at the todotxt.com page](http://todotxt.com/) the example in their screenshots at the top contain two items with priority `(A)`. Would you consider removing that check?

**Comment by hartez** [comment]
Fixed.
