### ISSUE TITLE
Colour doesn't get reset

### ISSUE THREAD

**Issue by mbuettner** [hartez/todo.txt-PowerShell#9]
I just installed the module on PS5, Windows 10, and it seems that the colours don't get reset after running `todo`:

![todo-colour](https://cloud.githubusercontent.com/assets/1846708/10275872/5d64b4f0-6b4b-11e5-9f0e-762c3f6287c6.png)

I don't experience this using PS3 on Windows 8.

**Comment by hartez** [comment]
I just tested it, and it seems that it only happens if the very last task in the list is a priority task. I'll try to find a fix for that today.

**Comment by mbuettner** [comment]
That sort of makes sense, because the if the last task is a non-priority
task, the colour will already be reset to white (because that's the task's
colour).

**Comment by hartez** [comment]
Now resets the color after displaying the list.
